-- create_supabase_tables.sql
-- This script creates the necessary tables for the Decenter AI project in Supabase (PostgreSQL).
-- Run this in the Supabase SQL Editor or via psql in your development environment.
-- Ensure you are connected to the correct database.

-- Create user_profiles table
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  firstname TEXT NULL,
  email TEXT NULL,
  wallet TEXT NULL,
  unreal_token TEXT NULL,
  calls BIGINT NULL DEFAULT '0'::BIGINT,
  is_admin BOOLEAN NULL DEFAULT FALSE,
  is_active BOOLEAN NULL DEFAULT TRUE,
  lastname TEXT NULL,
  username TEXT NULL,
  bio TEXT NULL,
  profile_image TEXT NULL,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_email_key UNIQUE (email),
  CONSTRAINT user_profiles_unreal_token_key UNIQUE (unreal_token),
  CONSTRAINT user_profiles_wallet_key UNIQUE (wallet)
) TABLESPACE pg_default;

-- Create chat_history table
CREATE TABLE IF NOT EXISTS public.chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "user" BIGINT NULL,
  user_message TEXT NULL,
  ai_response TEXT NULL,
  model TEXT NULL,
  object TEXT NULL,
  CONSTRAINT chat_history_pkey PRIMARY KEY (id),
  CONSTRAINT chat_history_user_fkey FOREIGN KEY ("user") REFERENCES public.user_profiles (id)
) TABLESPACE pg_default;

-- Create api_keys table
CREATE TABLE IF NOT EXISTS public.api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "user" BIGINT NOT NULL,
  provider TEXT NOT NULL,
  api_key TEXT NOT NULL,
  api_hash TEXT NULL,
  api_name TEXT NULL,
  payment_token TEXT NULL,
  calls DOUBLE PRECISION NULL,
  chain_id BIGINT NULL,
  last_used TIMESTAMP WITHOUT TIME ZONE NULL,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_api_key_key UNIQUE (api_key),
  CONSTRAINT api_keys_user_fkey FOREIGN KEY ("user") REFERENCES public.user_profiles (id)
) TABLESPACE pg_default;